Planning-Inspectorate/common-pipeline-templates

steps/terragrunt_validate.yml
Add a terragrunt validate step template
=> Add Terragrunt validate step

steps/run_checkov.yml, steps/terraform_format.yml, steps/terragrunt_hclfmt.yml
- Adds steps for formatting terraform code
- Adds step to run checkov, takes parameters to publish test results, skip checks
=> Add steps for terraform formatting and checkov

steps/git_tagging.yml
Forgot to save the file for git tags 🙈
=> Add git tagging step

jobs/wrapper_job.yml, stages/wrapper_ci.yml, stages/wrapper_stage.yml, steps/azure_cli_login.yml, steps/run_checkov.yml, steps/terraform_format.yml, steps/terraform_tflint.yml, steps/terragrunt_apply_all.yml, steps/terragrunt_hclfmt.yml, steps/terragrunt_plan_all.yml, steps/terragrunt_validate_all.yml
- Adds a new wrapper template for CI pipelines
- Adds a new wrapper template for jobs and stages, which should mean less code to write, and we can set variables, generic steps etc. later on
- Adds some more logging to script steps and fix an issue with TFLint not running in modules
=> Add wrapper templates for stages, job, and CI pipelines

jobs/wrapper_deployment.yml, jobs/wrapper_job.yml, stages/wrapper_cd.yml, stages/wrapper_ci.yml, stages/wrapper_stage.yml, steps/azure_cli_login.yml, steps/terragrunt_apply_all.yml, steps/terragrunt_plan_all.yml
- Add wrapper template for CD pipeline
- Fix Apply step and pass artifact between Plan and Apply
- Had to change how the Service Connection is done as the AzureCLI task doesn't accept dynamic values, instead we construct via parameters that are available at compile time
=> Add CD stage wrapper, job and deployment wrappers

stages/wrapper_cd.yml, stages/wrapper_ci.yml, steps/azure_web_app_acr_push.yml
- Update parameters in CI wrapper stage
=> Update parameters since login step moved into wrapper template

jobs/wrapper_deployment.yml, stages/wrapper_cd.yml, steps/terraform_apply.yml, steps/terragrunt_plan.yml, steps/terragrunt_plan_all.yml
- Add a new terragrunt plan step
- We can use the terraform apply step as the terragrunt plan step outputs a plan file
=> Add terragrunt plan apply steps for deploying individual stack

stages/wrapper_web_app_cd.yml, steps/terragrunt_plan.yml
- Allow passing key vault variables into web app deploy wrapper
- Fix Terragunt plan step reporting success when error occurred
=> Add Key vault variables to web app wrapper & fix Terragrunt plan step reporting success on error

steps/azure_web_app_acr_push.yml
Add optional steps to run and publish test results. Assumes tests run in a multi-stage Dockerfile.
=> feat(steps/azure_web_app_acr_push.yml): add steps to run tests

jobs/cypress_e2e_tests.yml
Skip artifact publish if the folder does not exist
=> fix(cypress): artifact publishing

steps/azure_auth.yml, steps/azure_get_secrets.yml, steps/azure_web_app_acr_push.yml, steps/azure_web_app_deploy.yml, steps/node_script.yml
Add additional error handling in scripts to ensure pipeline exits with an error.
=> fix(templates): error handling

steps/azure_web_app_slot_deploy.yml, steps/azure_web_app_slot_swap.yml
- Add a step to deploy a container to a specific App Service slot (e.g. to a staging slot).
- Add a step to swap an App Service slot (e.g. from staging to production).
=> Steps for App Service Slots

steps/azure_web_app_slot_swap.yml
- Fix conditional statement in `azure_web_app_slot_swap.yml` step.
=> Fix condition in slot swap step

steps/azure_web_app_deploy.yml, steps/terraform_apply.yml, steps/terraform_plan.yml, steps/terragrunt_plan.yml
Moved Terraform Apply skip logic into the Apply step instead of the Plan step.
=> fix(templates): move terraform apply skip logic

jobs/wrapper_deployment.yml, steps/terraform_apply.yml, steps/terraform_plan.yml
- Add *.tftpl files to the artifact produced by the Terraform Plan step
- Ensure deployment jobs download artifacts from current pipeline
=> Fix Terraform Apply step when Plan includes template files

jobs/wrapper_job.yml, stages/wrapper_cd.yml
- Abstracts the `timeoutInMinutes` pipeline job attribute to both the job wrapper and CD wrapper pipeline templates.
=> Add support for configurable job timeout

jobs/wrapper_deployment.yml, stages/wrapper_cd.yml
pass through depends on param down to wrapper_job.yml
to allow deploymentJobs stages/wrapper_cd.yml to set dependsOn
=> feat: allow dependsOn for deployment jobs

steps/azure_container_registry_purge.ps1, steps/azure_container_registry_purge.yml
https://pins-ds.atlassian.net/browse/DEV-325
Pipeline to purge images for a given set or repositories, checking last modified and image tags in use by app services.
=> feat: azure_container_registry_purge.yml

steps/azure_container_registry_purge.ps1
Small fix to ensure apps listed using an image are correct (needed to be scoped by repo)
=> fix: match images by tag correctly, must be grouped by repo

variables/environments/staging.yml
Adding staging environment yaml file for appeals service
=> feat(infrastructure): adding staging environment variable yaml file
